env_type: safe_grid_gym
env_setup:
  _target_: envs.randomfrozenlake.RandomFrozenLakeEnv
  seed: ${seed}
  is_slippery: true
  map_name: null
env_id: DistributionalShift-v0

norm_reward: false

terminates: true
traj_len: 100

start_train_ep: 1000
train_freq_ep: 100

start_train_step: 10000
train_freq_step: 1000


